# Generated by Django 5.0.7 on 2024-07-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="tournaments", to="user.player"
            ),
        ),
    ]
